### ISSUE TITLE
Widen text for mobile

### ISSUE THREAD

**Issue by dwarkeshsp** [slashformotion/hugo-tufte#12]
Is there any way to widen the text max-width for mobile? Unlike the actual Tufte CSS [example](https://edwardtufte.github.io/tufte-css/), this template seems to become awfully narrow on mobile. See image below of this template.

![example](https://user-images.githubusercontent.com/45517911/127781505-cf4e38c9-6857-4ee3-9e6c-e94d7f0adcd3.PNG)

If the website going to autohide the margin notes on narrow screens anyways, why not have the text use the full width on the screen? I'm not sure what part of the CSS controls this width, but I'll keep looking. In the meantime, if you happen to know where it is and can change it, that would be greatly appreciated.

No rush or pressure! I appreciate that you are maintaining this template and I have no expectation for you to fulfill special requests like these.

**Comment by slashformotion** [comment]
that's seems a good thing to do. I will probably convert the css to scss for more flexibility

**Comment by slashformotion** [comment]
@dwarkeshsp I tested this issue on my phone and it doesn't happen. I think this is because of the responsive module of the chrome dev tools

**Comment by dwarkeshsp** [comment]
Yup, you're right! I was mistaken. Thanks a lot for checking!
