### ISSUE TITLE
Markdown in marginnote

### ISSUE THREAD

**Issue by vicmortelmans** [slashformotion/hugo-tufte#18]
Hi, I'm not sure if this is a bug or a feature request, but I was surprised that marginnotes don't take markdown as input. The input is litterally copied into the HTML, so HTML is accepted.

Is this a stringent limitation of the theme?

Best regards,
Vic

**Comment by slashformotion** [comment]
Actually the marginote render as follow

```html
{{ $marginnoteDomIdSuffix := .Ordinal }}
<label
  for="marginnote-{{.Page.File.UniqueID}}-{{ $marginnoteDomIdSuffix }}"
  class="margin-toggle"
  >&#8853;
</label>
<input
  type="checkbox"
  id="marginnote-{{.Page.File.UniqueID}}-{{ $marginnoteDomIdSuffix }}"
  class="margin-toggle"
/>
<span class="marginnote">{{ .Inner }}</span>
```

Its not a theme limitation, it's just that you can't render markdown in shortcode natively. They are rendered "as is".

***But that's actually fixable***

**Comment by slashformotion** [comment]
@vicmortelmans Thanks for your contribution
