### ISSUE TITLE
Two deprecation warnings for _normalize-mixin.scss

### ISSUE THREAD

**Issue by rprechelt** [slashformotion/hugo-tufte#37]
## What version of Go are you using (`$ hugo version`)?
v0.80.0/extended

## What operating system and processor architecture are you using?
Linux, Fedora 33, x86-64

## What did you do?
Running `hugo server` with a fresh clone of `hugo-tufte` in an empty project

## What did you expect to see?
No errors or deprecation warnings.

## What did you see instead?
Two deprecation warnings for the `_normalize-mixin.scss` file.

```
DEPRECATION WARNING on line 16 of /path/to/site/themes/hugo-tufte/assets/scss/vendor/normalize/_normalize-mixin.scss:
!global assignments won't be able to declare new variables in future versions.
Consider adding `$-normalize-include: null` at the top level.

DEPRECATION WARNING on line 16 of /path/to/site/themes/hugo-tufte/assets/scss/vendor/normalize/_normalize-mixin.scss:
!global assignments won't be able to declare new variables in future versions.
Consider adding `$-normalize-exclude: null` at the top level.
```
Adding `$-normalize-exclude: null` and `$-normalize-include: null` to the top of `_normalize-mixin.scss` removes the deprecation error but I'm as I'm not familiar with SCSS, I'm not sure if this has unintended consequences elsewhere in the project.

If adding these lines is not an issue, it would be good to add them to the repo and remove some of the "deprecation" noise for users. I can open an MR if needed.

**Comment by slashformotion** [comment]
It was really fixed in [this commit](https://github.com/slashformotion/hugo-tufte/commit/affe4f6c8119cb83fef2c420bbbbfaab7b7fb671)
