### ISSUE TITLE
Permalinks aren't supported

### ISSUE THREAD

**Issue by zohaad** [slashformotion/hugo-tufte#4]
Writing
```
permalinks:
  /: /:filename/
```
in `config.yaml` doesn't appear to change the url format.

**Comment by slashformotion** [comment]
Although hugo support `.yml` files for configuration, usualy people use `.toml`. I am not really good with YML, but i will  do my best.

@zohaad can you give me a bit of context to solve this ? 

1. What version of Go are you using (`$ hugo version`)?
2. What operating system do you use?
3. What did you do?
4. What did you expect to see?
5. What did you see instead?

**Comment by slashformotion** [comment]
It's a problem not linked with the theme but with your code or hugo. check this https://gohugo.io/content-management/urls/
