### ISSUE TITLE
Not sure if this is a bug or not: Second level bullet lists have short lines

### ISSUE THREAD

**Issue by mdtdev** [slashformotion/hugo-tufte#46]
I believe that this is a bug, but if it is a style choice that is part of the Tufte system, I apologize. I cannot find anything that indicates that this is a stylistic choice.

## What version of Go are you using (`$ hugo version`)?

`hugo v0.90.1-48907889+extended windows/amd64 BuildDate=2021-12-10T10:56:41Z VendorInfo=gohugoio`

Installed with [chocolatey](https://chocolatey.org/) for Windows. 

## What operating system and processor architecture are you using?

Windows 10 Home, Intel i5. I see similar results with another Windows computer running 10 Pro.

## What did you do?

I created a bulleted list with the usual hugo/markdown procedure. Here is example code that reproduces the error on several Tufte pages where I inserted it:

```Markdown
Here is a bullet list:

- Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
- Arcu felis bibendum ut tristique et. Volutpat odio facilisis mauris sit amet massa.
- Sed id semper risus in hendrerit gravida rutrum.
  - Risus pretium quam vulputate dignissim suspendisse in est ante. Bibendum neque egestas congue quisque egestas diam in arcu.
  - Nulla porttitor massa id neque aliquam. Laoreet non curabitur gravida arcu ac tortor dignissim convallis.
- Sit amet consectetur adipiscing elit.
```
The problematic behavior is in the indented items on the list.

## What did you expect to see?
I expected to see all of the lines extend to the same right-hand boundary for word-wrapping. That is, I expected the indented lines to go to the same right boundary as the un-indented items.

## What did you see instead?
The second-level (indented) bullets are on lines that are about half the length of the first-level lines. 

**Is this the normal behavior for the Tufte style? I could not find examples showing it as clearly intentional nor did I see it elsewhere.**

Here is what it looks like for me:

![image](https://user-images.githubusercontent.com/9751401/146079053-5af3233c-2efb-478a-82a6-4a891479b704.png)

## Optional (best if completed)

**To Reproduce**
1. On any page add the code snippet above. (I tested in on the example site pages with the theme; specifically by adding the code to the `about` page and to one of the blog entry type pages.)
2. Render the page (`hugo serve -D`).
3. Look at the served page.

**Comment by slashformotion** [comment]
I'll look into it

**Comment by slashformotion** [comment]
Fixed !
