### ISSUE TITLE
Mobile view of Tufte theme appears to hide one picture (on demo site)

### ISSUE THREAD

**Issue by mdtdev** [slashformotion/hugo-tufte#52]
## What version of Hugo are you using (`$ hugo version`)?
`hugo v0.90.1-48907889+extended windows/amd64 BuildDate=2021-12-10T10:56:41Z VendorInfo=gohugoio` (for Windows part)

## What operating system and processor architecture are you using?
Intel chip, windows 10 for the regular browser view and the simulated iPhone views. Samsung Galaxy S10e for the real mobile views. 

## What did you do?
I built the test website and viewed it in Chrome as an "iPhone 12 Pro" form factor (via the developer tools). I did this same thing using the demo website ( https://slashformotion.github.io/hugo-tufte/post/tufte-features/ ) and got the same result. Results replicated on my Samsung S10e phone (included in pictures below).

## What did you expect to see?
I expected to see the mobile view of the page, with all figures working. However, the "plus sign" for opening and closing figures does not work correctly (for ONE of the figures, the rest are ok).

This is the page viewed in a browser under windows 10:

![hugo-tufte-working-page-01](https://user-images.githubusercontent.com/9751401/156022422-8afe4318-cd7c-4d73-a41c-ebca5a124434.png)

## What did you see instead?
Specifically, the picture of the Rhino does not appear and pressing either of the "plus signs" near it just open the caption for a different figure. Nothing I do makes the rhino figure appear. I believe that the lower plus sign in the figure shown below is supposed to reveal and hide the rhino figure.

Here are two mobile views (Samsung), with various states shown. The two plus signs (both) only control the caption on the visible figure. The rhino does not appear, even if the view is moved to look at the whitespace on the right:

With caption:
![hugo-tufte-on-phone-w-caption-arrows](https://user-images.githubusercontent.com/9751401/156022837-885cd5d3-d449-4d28-b72d-39dfb9d6daa8.jpg)

Without caption:
![hugo-tufte-on-phone-w-o-caption](https://user-images.githubusercontent.com/9751401/156022891-cee07aee-b59a-4232-9aad-494c0840a441.jpg)

If I can provide any more information, please let me know.

**To Reproduce**
1. Go to https://slashformotion.github.io/hugo-tufte/post/tufte-features/
2. Open on a mobile device.
3. Compare with the full sized web page in a desktop or laptop browser.
4. Try to find the rhino.

**Comment by slashformotion** [comment]
hum thanks for the issue,  I will look into it

**Comment by slashformotion** [comment]
I don't have the time to work on it, i will close this issue: this repository is gonna be archived
